### PR TITLE
#5 - adjust the post type registry to not show in REST, not show in nav menus, etc

### LINKED ISSUE #5: The Action Monitor post type registry needs to be adjusted
The Action Monitor post type has exclude_from_search set to false, so Action Monitors can show up in the Wordpress site search. I assume that this is not intentional.

See line 987 here: https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/ActionMonitor.php

### PR DESCRIPTION
**Pull request by jasonbahl**
Closes #5 

This updates the post type registry for the Action Monitor post type to:

- not show in search
- not show in the REST API
- not show in nav menus

### CODE REVIEW

**Comment by TylerBarnes** [comment]
@jasonbahl this looks good! Have you run the source plugin with these changes?

**Comment by jasonbahl** [comment]
@TylerBarnes I have not. . .with the new Docker setup should be a breeze though, eh? 👀

**Comment by TylerBarnes** [comment]
I'm not so sure actually haha. I'd probably test this with Local since the docker setup will install a specific version of WPGatsby but this isn't published yet

**Comment by TylerBarnes** [comment]
I just pulled it down and tested it out and it's working great. Thanks @jasonbahl !

**Review by TylerBarnes — APPROVED** [review]

**Pull request merged**
