### PR TITLE
fix wrong arg count for wp_save_image_editor_file

### LINKED ISSUE #106: Unable to edit images in wp backend - Uncaught ArgumentCountError on callback_wp_save_image_editor_file
Hello guys,
I'm having an issue with image editing (e.g cropping) causing a fatal error.

The error happens when pressing save after doing an image edit (crop, scale, flip, resize etc) – admin-ajax gets a `500` status.
I've checked and confirmed this is happening on a fresh install on a sepapate environment (local) as well.

```
PHP 7.3.21

WP 5.4.4
WP Gatsby 0.9.2
```

Here is the error log and stack trace:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WPGatsby\\ActionMonitor\\Monitors\\MediaMonitor::callback_wp_save_image_editor_file(), 
1 passed in /my/site/wp-includes/class-wp-hook.php on line 289 and exactly 5 expected in 
/my/site/wp-content/plugins/wp-gatsby---latest/src/ActionMonitor/Monitors/MediaMonitor.php:136

Stack trace:
#0 /my/site/wp-includes/class-wp-hook.php(289): WPGatsby\\ActionMonitor\\Monitors\\MediaMonitor->callback_wp_save_image_editor_file(NULL)
#1 /my/site/wp-includes/plugin.php(206): WP_Hook->apply_filters(NULL, Array)
#2 /my/site/wp-admin/includes/image-edit.php(346): apply_filters('wp_save_image_e...', NULL, '/my/site...', Object(WP_Image_Editor_Imagick), 'image/jpeg', 27591)
#3 /my/site/wp-admin/includes/image-edit.php(853): wp_save_image_file('/my/site in /my/site/wp-content/plugins/wp-gatsby---latest/src/ActionMonitor/Monitors/MediaMonitor.php on line 136, referer: https://mysite.com/wp-admin/post.php?post=27591&action=edit
```

Let me know if you need any more info.

### PR DESCRIPTION
**Pull request by rburgst**
- also fix `wp_save_image_file` callback arg count

fixes #106

### CODE REVIEW

**Comment by rburgst** [comment]
@jasonbahl anyone home?

**Comment by jasonbahl** [comment]
@rburgst i actually am off this week 😆. But we can get this merged

**Comment by jasonbahl** [comment]
@TylerBarnes this PR is good if you want to merge and release it 😉

**Comment by TylerBarnes** [comment]
This is published in v1.0.3. Thanks @rburgst !

**Pull request merged**
